### ISSUE TITLE
Assistance with input fields

### ISSUE THREAD

**Issue by r0sies** [FofanovLab/VaST#1]
Hi,
Thanks for publishing this software. It looks really interesting. 
I was wondering if you could please describe the PROJECT_DIR input field required. I have tried with both a 'directory name' and a 'path to a directory' but for both, I received the error:
AMPLICON_FILTER: error: argument PROJECT_DIR: Not a valid path

Thank you!

**Comment by tfursten** [comment]
@r0sies Are you trying to run the preprocessing module or the pattern_selection module and what operating system are you using? The code that parses the argument is below. It should be a valid directory according to `os.path.isdir`. 
```
def path_type(input_path):
    if not os.path.isdir(input_path):
        raise argparse.ArgumentTypeError("Not a valid path")
    return os.path.abspath(input_path)
```

**Comment by r0sies** [comment]
Hi,
I was running the pre-processing module on a unix hpc. Thanks, Rosie

**Comment by r0sies** [comment]
Hi,
I tested: 
print os.path.isdir("/project/vast_test/")

and received True

Is there something else I needed to add? Thanks

**Comment by r0sies** [comment]
I was playing around and I added debugging code:
def path_type(input_path):
    if not os.path.isdir(input_path):
        raise argparse.ArgumentTypeError("Not a valid path: " + os.path.abspath(input_path))
    return os.path.abspath(input_path)


def file_type(input_file):
    if not os.path.isfile(input_file):
        raise argparse.ArgumentTypeError("Not a valid file path: " + os.path.abspath(input_file))
    return os.path.abspath(input_file)

but now the error I receive is:
AMPLICON_FILTER: error: argument VAR_MATRIX_PATH: Not a valid file path: <PROJECT_DIR path>
