### ISSUE TITLE
How to convert vcf to site matrix file

### ISSUE THREAD

**Issue by r0sies** [FofanovLab/VaST#2]
Hi,
Do you have any recommendations on how to convert VCF files to a variant site matrix? thanks, Rosie

**Comment by tfursten** [comment]
I use scikit-allel to parse the vcf files and do any filtering. You can use `vcf_to_dataframe(filename.vcf)` to create a dataframe to modify and convert the dataframe into the appropriate format.

**Comment by r0sies** [comment]
Thanks for this Tara. Do you happen to have any scripts you could point me to, to convert the dataframe into the variant site matrix? Thanks, Rosie

**Comment by r0sies** [comment]
Thanks Tara! I think resolved this using: bcftools query -f '%CHROM:%POS\t%REF[\t%TGT]\n' study.vcf.gz
